# site settings
title: Pista ng Mapa 2023
description: "a free and open mapping conference in the Philippines"
email: "pistangmapa@gmail.com"
baseurl: "/2023"
logo: "/assets/img/logos/pnm-sq.png"
nav-logo: "/assets/img/logos/pnm-nav-logo.png"
favicon: favicon.ico
repo_address: "pistangmapa/2023"
messenger: ""
facebook: "PistaNgMapaPH"
twitter: "pistangmapa"
instagram: ""
mastodon: "@pistangmapa"
telegram: "pistangmapa"
github: "pistangmapa"
yt-stream-link: ""

# tito event
tito-event: "pistangmapa/2021-online"

# exclude
exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - vendor/bundle/

# build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

# plugins
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from

#secondary category id
secondary_category:
    -
     title: "Blueprints of Progress: The Role of Mapping in Urban Development"
     scid: "acad1"
    -
     title: "Unveiling Insights: Using Geospatial Data to Analyze Situations and Craft Compelling Stories"
     scid: "light1"
    -
     title: "Mapping the Future: Geospatial Data's Role in Shaping Our World"
     scid: "gene1"
    -
     title: "Data-Driven Governance: Understanding Environment and Society through Mapping"
     scid: "acad2"
    -
     title: "Fueling Progress: Leveraging Open Data for Technological, Infrastructure, and Community Development"
     scid: "light2"
    -
     title: "Fostering Excellence in Open Mapping: Capacity Building and Skill Elevation Initiatives"
     scid: "gene2"
    -
     title: "Earth's Treasure Map: Mapping Natural Resources for Sustainable Development"
     scid: "acad3"
    -
     title: "YouthMapping the Future: Showcasing YouthMappers Chapters' Projects and Initiatives in the Philippines"
     scid: "light3"
    -
     title: "Exploring Frontiers: AI, Geo Innovation, and Mythical Realities - A Multifaceted Talk Series"
     scid: "gene3"
#presentors
presentors:
    -
     name: "Mr. Mikko Tamura"
     category: "Plenary"
     scid: "0"
     link: ""
     talk_title: "From Pixels to Purpose: Our journey and our learnings"
     position: "Community Manager"
     affiliation: "Open Mapping Hub Asia Pacific"
    -
     name: "Dr. Alfredo Mahar Francisco Lagmay"
     category: "Plenary"
     scid: "0"
     link: ""
     talk_title: "Citizen Science, Open Data and Public Good"
     position: "Director"
     affiliation: "UP Resilience Institute"
    -
     name: "Ben Hur Pintor"
     category: "Open"
     scid: "0"
     link: ""
     talk_title: "Sponsor's Talk"
     position: "Charter Member"
     affiliation: "OSGeo"
    -
     name: "Wilfredo Dizon Jr"
     category: "Academic"
     scid: "acad1"
     link: ""
     talk_title: "Utilizing OpenStreetMap Building Footprint Data for Urban Planning and Disaster Risk Reduction in the Municipality of Laguna"
     position: ""
     affiliation: "LGU Luna, La Union"
    -
     name: "Bryan Steven Borja"
     category: "Academic"
     scid: "acad1"
     link: ""
     talk_title: "Secured By Design: Establishing Design Guidelines Against Crime in Urban Communities of Tacloban City"
     position: ""
     affiliation: "Cali Architects"
    -
     name: "Mia Kristine Cami単a Quinco"
     category: "Academic"
     scid: "acad2"
     link: ""
     talk_title: "Beyond the Choropleth: How UP Mindanao mapping efforts help shape Davao City policies and disease Intervention programs"
     position: ""
     affiliation: "UP Mindanao YouthMappers"
    -
     name: "Ervina Espina"
     category: "Academic"
     scid: "acad2"
     link: ""
     talk_title: "Mental maps as spatial representations: the case of displaced informal settlers post-Haiyan"
     position: ""
     affiliation: "UP Tacloban"
    -
     name: "Jeremy Romero"
     category: "Academic"
     scid: "acad3"
     link: ""
     talk_title: "Still Waters Run Deep: Uncovering the Bathymetric and Morphometric Profile of Lake Danao in Ormoc City, Leyte, Philippines"
     position: ""
     affiliation: "UP Tacloban"
    -
     name: "Jan Rovic Cueto"
     category: "Academic"
     scid: "acad3"
     link: ""
     talk_title: "Identification of Paterns of Thermal Unrest in Taal Volcano Using Remote Sensing"
     position: ""
     affiliation: "Rizal Technological University"
    -
     name: "Jerome Jack Oben Napala"
     category: "Academic"
     scid: "acad3"
     link: ""
     talk_title: "Spatial Mapping of Marine Resources for Inclusive Comprehensive Land Use Planning in Sogod, Southern Leyte"
     position: ""
     affiliation: "SLSU YouthMappers"
    -
     name: "Leanne Caye Obispo"
     category: "Lightning"
     scid: "light1"
     link: ""
     talk_title: "Data: A Story to Tell"
     position: ""
     affiliation: "UP Diliman, UP GEOP"
    -
     name: "Paolo Lorenzo Lora"
     category: "Lightning"
     scid: "light1"
     link: ""
     talk_title: "Rediscovering Local History Through Cultural Mapping"
     position: ""
     affiliation: "UP Tacloban YouthMappers"
    -
     name: "Denrazir Atara"
     category: "Lightning"
     scid: "light1"
     link: ""
     talk_title: "Web Visualization and Spatial Analysis of Tree Species Distribution at University of the Philippines Diliman Academic Oval"
     position: ""
     affiliation: "USTP YouthMappers"
    -
     name: "Jorton Agda Tagud"
     category: "Lightning"
     scid: "light1"
     link: ""
     talk_title: "Exposure of Southern Leyte Pacific Towns to Possible Earthquake Induced Tsunami"
     position: ""
     affiliation: "SLSU YouthMappers"
    -
     name: "Mark Aimon Pangan"
     category: "Lightning"
     scid: "light2"
     link: ""
     talk_title: "COLABDev: Data-Driven Development in Palimbang, Sultan Kudarat"
     position: ""
     affiliation: "Action for Economic Reforms"
    -
     name: "Jikka Defi単o"
     category: "Lightning"
     scid: "light2"
     link: ""
     talk_title: "POIs for greenfield hyperscale data center site selection"
     position: ""
     affiliation: "OSM Philippines, HOT, Jones Lang LaSalle"
    -
     name: "Joyce Mae Callao"
     category: "Lightning"
     scid: "light2"
     link: ""
     talk_title: "Mapping for Resilience"
     position: ""
     affiliation: "USTP YouthMappers"
    -
     name: "Ben Hur Pintor"
     category: "Lightning"
     scid: "light2"
     link: ""
     talk_title: "Beyond shapefiles and file-based data management"
     position: ""
     affiliation: "BNHR"
    -
     name: "Yhogen Boy Villacite Julve"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "Mapping Fire Hydrants as Baseline Data for Fire Emergency Response in Leyte Province, Philippines"
     position: ""
     affiliation: "Viscan YouthMappers"
    -
     name: "Erika Del Rosaria and Pauline Jen Madrona"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "Soaring to New Heights: UPRI YouthMappers' First Drone Training"
     position: ""
     affiliation: "UPRI YouthMappers"
    -
     name: "Lanz Bartolome"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "Optimizing Field Data Collection: Leveraging KoboToolbox in USTP YouthMappers Projects"
     position: ""
     affiliation: "USTP YouthMappers"
    -
     name: "Oriel Jay Iba単ez"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "Enhancing Community Development Through Drone Imaging in Tacloban City"
     position: ""
     affiliation: "UP Tacloban YouthMappers"
    -
     name: "Shrine Angeli Aparejo"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "A Yearlong Journey with Southern Leyte State University YouthMappers in Open Mapping"
     position: ""
     affiliation: "SLSU YouthMappers"
    -
     name: "Mia Kristine Cami単a Quinco"
     category: "Lightning"
     scid: "light3"
     link: ""
     talk_title: "Igniting UP Mindanao's Passion and Interest in GIS and Open Mapping: An SLSI Legacy"
     position: ""
     affiliation: "UP Mindanao YouthMappers"
    -
     name: "Salim Baidoun"
     category: "General"
     scid: "gene1"
     link: ""
     talk_title: "It takes the world to map the world"
     position: ""
     affiliation: "TomTom"
    -
     name: "Ben Hur Pintor"
     category: "General"
     scid: "gene1"
     link: ""
     talk_title: "Mapping the road less traveled: Building careers with open geospatial"
     position: ""
     affiliation: "BNHR"
    -
     name: "Dinnah Faye Andal"
     category: "General"
     scid: "gene2"
     link: ""
     talk_title: "Elevating Skills in the Philippines: Introduction to YouthMappers UpSkilling Series"
     position: ""
     affiliation: "YouthMappers"
    -
     name: "Mikko Tamura"
     category: "General"
     scid: "gene2"
     link: ""
     talk_title: "Pave the way for the Open Mapping Gurus"
     position: ""
     affiliation: "Open Mapping Hub Asia Pacific"
    -
     name: "Luis Caezar Ian Panganiban"
     category: "General"
     scid: "gene3"
     link: ""
     talk_title: "AI for Geo: A Gentle Introduction to AI for the Geo Industry"
     position: ""
     affiliation: "Ausome Maps / AusomeCo"
    -
     name: "Ben Hur Pintor"
     category: "General"
     scid: "gene3"
     link: ""
     talk_title: "Why you shouldn't use QGIS: new and upcoming features (2023 edition)"
     position: ""
     affiliation: "BNHR"
    -
     name: "Dino Evangelista"
     category: "General"
     scid: "gene3"
     link: ""
     talk_title: "Mythical Creatures, Real Hazards: Co-creating and co-designing story maps of local folklore, beliefs, and myths about the environment"
     position: ""
     affiliation: "UPRI - UP NOAH Center"